### ISSUE TITLE
Add form to insert new article

### ISSUE THREAD

**Issue by MarcoTribuz** [Realise-Formation-Digital/Bootstrap-SportNewspaper#4]
The form ( on a new page ) must have

- name field
- surname
- email
- date of article
- textarea where write the article

the form should check

- email should have this pattern --> yourName@yourDomain.com
- date of book should have this pattern --> DD/MM/AAAA
- text area should accept 250 characters max

after this checks, show an alert with the data inserted

**Comment by axelduret** [comment]
this issue is for Dario

**Comment by DarguiGago24** [comment]
Thank's
